apiVersion: apps/v1
kind: Deployment
metadata:
  name: project1-deployment
  labels:
    app: project1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: project1
  template:
    metadata:
      labels:
        app: project1
    spec:
      containers:
      - name: project1
        image: ajithkumar2585/project2
        ports:
        - containerPort: 80
